/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: akshatmittal (https://sketchfab.com/akshatmittal)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/iphone-14-pro-max-95f11f5a06604c8b9fd44046ae52a9cc
title: iPhone 14 Pro Max
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Group } from "three";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
	nodes: {
		lxsKwuOPNvmzBKg_0: THREE.Mesh;
		alSOKOYgFKIcUtR: THREE.Mesh;
		FjhETOCBEeiBmch: THREE.Mesh;
		AbxQOpRbGREHXRG: THREE.Mesh;
		tWfjYtMZCfucxRt: THREE.Mesh;
		XbtrdVaOWYmkEiU: THREE.Mesh;
		YbXWdqEcjbfTKuN_0: THREE.Mesh;
		rrqFqyfckTuyRuI: THREE.Mesh;
		OMkeKbwVHRBkBwM: THREE.Mesh;
		DLfIUIalXuQjJsL: THREE.Mesh;
		KABLQLZRuEbcLWk: THREE.Mesh;
		qjXEDwnnBYwWcJn: THREE.Mesh;
		FGDSbHbILfUmiaH: THREE.Mesh;
		jQXfQpudiYObSGp: THREE.Mesh;
		knexoFNknstHgiO: THREE.Mesh;
		FaUtifOQSMTXiZM: THREE.Mesh;
		BhvzCWikxrVeDTV: THREE.Mesh;
		MMkajxMNWrwGQfi: THREE.Mesh;
		YnrVhXEUDbStWCs: THREE.Mesh;
		ePYqawqlCJbCsNi: THREE.Mesh;
		RGbIswEcCTzqNsn_0: THREE.Mesh;
		IuMgFUHIyRWENxG_0: THREE.Mesh;
		dNDonqESZOxUcei_0: THREE.Mesh;
		XeFHhVBtRZWPGxR: THREE.Mesh;
		nJYGEbPQybRBbiN: THREE.Mesh;
		JyAbjubWrOdfygC_0: THREE.Mesh;
		nxFoHsySvfcSLvp: THREE.Mesh;
		oCklTGvTZoDWJrC_0: THREE.Mesh;
		vauUojKrKkLLDtY: THREE.Mesh;
		yqmgDmvGsmuPwXx_0: THREE.Mesh;
		wjSYkRykuFHJNPw: THREE.Mesh;
		rJeCWUNsVVXXAbI: THREE.Mesh;
		rqSonbcVVSPWFfa_0: THREE.Mesh;
		tWBbDznHihIxXam: THREE.Mesh;
		PLFTnNQeqVAxicS: THREE.Mesh;
		GWEiavWnRxbogtw_0: THREE.Mesh;
		RFqaqXLpuCDBIGV_0: THREE.Mesh;
		JUTNJcWwqyxbGDZ_0: THREE.Mesh;
		BDLCJBydsNjizog_0: THREE.Mesh;
		zPPSOvNamLQVyvv: THREE.Mesh;
		YPGjoywokSeoQFr: THREE.Mesh;
		MoTJNOoMxqdxNvQ: THREE.Mesh;
		mZxrNiCtMrMjOMv: THREE.Mesh;
		tQCDizUpBYNcvFA: THREE.Mesh;
		CAQeTxdpUcbxQyT: THREE.Mesh;
		qsTxqfACkdoWeLQ: THREE.Mesh;
		aVmapfDgqkPkjUf: THREE.Mesh;
		lgnGJJmNebyRbHq_0: THREE.Mesh;
		QaGkMzxNzKPcqRy: THREE.Mesh;
		KUDomTaVduCyevu: THREE.Mesh;
		QOfJIBEXOvXfSUh: THREE.Mesh;
		RUMRNTkptJGDMpy: THREE.Mesh;
		aYjPeBrpBRopJbp: THREE.Mesh;
		BeQtuLXtpSTrzAH: THREE.Mesh;
		UCttAeyROPsgmix: THREE.Mesh;
	};
	materials: {
		KhJiSWFcsscOusf: THREE.MeshStandardMaterial;
		sWxYOtHGWTcXRMx: THREE.MeshStandardMaterial;
		KtvhjlxyToKjYkE: THREE.MeshStandardMaterial;
		IDdMwJVCyuFpUnA: THREE.MeshStandardMaterial;
		fdfRsQCrfvPBPfQ: THREE.MeshStandardMaterial;
		YiceMpFVTpnmoaq: THREE.MeshStandardMaterial;
		GFNYbWjyDVGUwJd: THREE.MeshStandardMaterial;
		CSNzlRnZuvCyxNL: THREE.MeshStandardMaterial;
		IkWzRHNnDaKQXIi: THREE.MeshStandardMaterial;
		pBMikDFQfUOsKkr: THREE.MeshStandardMaterial;
		tfbCjiZQaZkmtHx: THREE.MeshStandardMaterial;
		LtesZnUOMbBEAoi: THREE.MeshStandardMaterial;
		EJpkIDZfhPDUzel: THREE.MeshStandardMaterial;
		FlDKBWPodPcEeGy: THREE.MeshStandardMaterial;
		LcWBQfBvCzxThpp: THREE.MeshStandardMaterial;
		LUbRMhkIhuekQRK: THREE.MeshStandardMaterial;
		tDZQoaroJfCIQtF: THREE.MeshStandardMaterial;
		jFPFAvCbiqflbQV: THREE.MeshStandardMaterial;
		HvAGJeQTAiWbceX: THREE.MeshStandardMaterial;
		bmOZLlCkCKhIIVe: THREE.MeshStandardMaterial;
		KxzouvBYEgdZhMo: THREE.MeshStandardMaterial;
		psePdsxZprlxGrw: THREE.MeshStandardMaterial;
		OStzgRHtVBLWwiD: THREE.MeshStandardMaterial;
		BLpVAsLWNICZYGG: THREE.MeshStandardMaterial;
		FsunUcGyajFpQmW: THREE.MeshStandardMaterial;
		nJRBoEsOhzMSqCz: THREE.MeshStandardMaterial;
		LJBezuBxKRoHnAp: THREE.MeshStandardMaterial;
		fGwijctGaiRaYJC: THREE.MeshStandardMaterial;
		qEGySvwsouNnVcn: THREE.MeshStandardMaterial;
		IBtgGxCVyZhjKZM: THREE.MeshStandardMaterial;
		WqbAhnIPgrrhfXS: THREE.MeshStandardMaterial;
		rNCplyWedyfORFh: THREE.MeshStandardMaterial;
		iEhZxWeNLTDdgxm: THREE.MeshStandardMaterial;
		vsSJQngPxBJTVZb: THREE.MeshStandardMaterial;
		xHgtbqndQshkTKG: THREE.MeshStandardMaterial;
		initialShadingGroup: THREE.MeshStandardMaterial;
	};
};

export const Iphone = (props: JSX.IntrinsicElements["group"]) => {
	const [rotateY, setRotateY] = useState(0);
	const ref = useRef<Group>(null!);
	const { nodes, materials } = useGLTF("/model/iphone/iphone.glb") as any as GLTFResult;

	useFrame(() => setRotateY((pre) => (pre += 0.01)));

	return (
		<group {...props} ref={ref} dispose={null} rotation={[0, rotateY, 0]} position={[0, -2, -5]}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.lxsKwuOPNvmzBKg_0.geometry}
						material={materials.KhJiSWFcsscOusf}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.alSOKOYgFKIcUtR.geometry}
						material={materials.sWxYOtHGWTcXRMx}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.FjhETOCBEeiBmch.geometry}
						material={materials.KtvhjlxyToKjYkE}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.AbxQOpRbGREHXRG.geometry}
						material={materials.IDdMwJVCyuFpUnA}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.tWfjYtMZCfucxRt.geometry}
						material={materials.fdfRsQCrfvPBPfQ}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.XbtrdVaOWYmkEiU.geometry}
						material={materials.YiceMpFVTpnmoaq}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.YbXWdqEcjbfTKuN_0.geometry}
						material={materials.GFNYbWjyDVGUwJd}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.rrqFqyfckTuyRuI.geometry}
						material={materials.CSNzlRnZuvCyxNL}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.OMkeKbwVHRBkBwM.geometry}
						material={materials.IkWzRHNnDaKQXIi}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.DLfIUIalXuQjJsL.geometry}
						material={materials.pBMikDFQfUOsKkr}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KABLQLZRuEbcLWk.geometry}
						material={materials.fdfRsQCrfvPBPfQ}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.qjXEDwnnBYwWcJn.geometry}
						material={materials.tfbCjiZQaZkmtHx}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.FGDSbHbILfUmiaH.geometry}
						material={materials.tfbCjiZQaZkmtHx}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.jQXfQpudiYObSGp.geometry}
						material={materials.sWxYOtHGWTcXRMx}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.knexoFNknstHgiO.geometry}
						material={materials.KtvhjlxyToKjYkE}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.FaUtifOQSMTXiZM.geometry}
						material={materials.KtvhjlxyToKjYkE}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.BhvzCWikxrVeDTV.geometry}
						material={materials.LtesZnUOMbBEAoi}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.MMkajxMNWrwGQfi.geometry}
						material={materials.LtesZnUOMbBEAoi}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.YnrVhXEUDbStWCs.geometry}
						material={materials.EJpkIDZfhPDUzel}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.ePYqawqlCJbCsNi.geometry}
						material={materials.CSNzlRnZuvCyxNL}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.RGbIswEcCTzqNsn_0.geometry}
						material={materials.FlDKBWPodPcEeGy}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.IuMgFUHIyRWENxG_0.geometry}
						material={materials.LcWBQfBvCzxThpp}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.dNDonqESZOxUcei_0.geometry}
						material={materials.LUbRMhkIhuekQRK}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.XeFHhVBtRZWPGxR.geometry}
						material={materials.tfbCjiZQaZkmtHx}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.nJYGEbPQybRBbiN.geometry}
						material={materials.tDZQoaroJfCIQtF}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.JyAbjubWrOdfygC_0.geometry}
						material={materials.jFPFAvCbiqflbQV}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.nxFoHsySvfcSLvp.geometry}
						material={materials.KtvhjlxyToKjYkE}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.oCklTGvTZoDWJrC_0.geometry}
						material={materials.tfbCjiZQaZkmtHx}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.vauUojKrKkLLDtY.geometry}
						material={materials.HvAGJeQTAiWbceX}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.yqmgDmvGsmuPwXx_0.geometry}
						material={materials.bmOZLlCkCKhIIVe}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.wjSYkRykuFHJNPw.geometry}
						material={materials.KxzouvBYEgdZhMo}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.rJeCWUNsVVXXAbI.geometry}
						material={materials.psePdsxZprlxGrw}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.rqSonbcVVSPWFfa_0.geometry}
						material={materials.jFPFAvCbiqflbQV}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.tWBbDznHihIxXam.geometry}
						material={materials.OStzgRHtVBLWwiD}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.PLFTnNQeqVAxicS.geometry}
						material={materials.BLpVAsLWNICZYGG}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.GWEiavWnRxbogtw_0.geometry}
						material={materials.FsunUcGyajFpQmW}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.RFqaqXLpuCDBIGV_0.geometry}
						material={materials.nJRBoEsOhzMSqCz}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.JUTNJcWwqyxbGDZ_0.geometry}
						material={materials.LJBezuBxKRoHnAp}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.BDLCJBydsNjizog_0.geometry}
						material={materials.fGwijctGaiRaYJC}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.zPPSOvNamLQVyvv.geometry}
						material={materials.qEGySvwsouNnVcn}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.YPGjoywokSeoQFr.geometry}
						material={materials.KtvhjlxyToKjYkE}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.MoTJNOoMxqdxNvQ.geometry}
						material={materials.IBtgGxCVyZhjKZM}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.mZxrNiCtMrMjOMv.geometry}
						material={materials.WqbAhnIPgrrhfXS}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.tQCDizUpBYNcvFA.geometry}
						material={materials.LtesZnUOMbBEAoi}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.CAQeTxdpUcbxQyT.geometry}
						material={materials.KtvhjlxyToKjYkE}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.qsTxqfACkdoWeLQ.geometry}
						material={materials.IBtgGxCVyZhjKZM}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.aVmapfDgqkPkjUf.geometry}
						material={materials.WqbAhnIPgrrhfXS}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.lgnGJJmNebyRbHq_0.geometry}
						material={materials.rNCplyWedyfORFh}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.QaGkMzxNzKPcqRy.geometry}
						material={materials.iEhZxWeNLTDdgxm}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KUDomTaVduCyevu.geometry}
						material={materials.KtvhjlxyToKjYkE}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.QOfJIBEXOvXfSUh.geometry}
						material={materials.vsSJQngPxBJTVZb}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.RUMRNTkptJGDMpy.geometry}
						material={materials.LJBezuBxKRoHnAp}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.aYjPeBrpBRopJbp.geometry}
						material={materials.xHgtbqndQshkTKG}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.BeQtuLXtpSTrzAH.geometry}
						material={materials.initialShadingGroup}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.UCttAeyROPsgmix.geometry}
						material={materials.KtvhjlxyToKjYkE}
					/>
				</group>
			</group>
		</group>
	);
};

useGLTF.preload("/iphone.glb");
