/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Lexyc16 (https://sketchfab.com/Lexyc16)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nissan-fairlady-z-s30240z-1978-0d9286ebb8cc426e993e1d398b874a34
title: Nissan Fairlady Z S30(240Z) 1978
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		Object_2: THREE.Mesh;
		Object_3: THREE.Mesh;
		Object_4: THREE.Mesh;
		Object_5: THREE.Mesh;
		Object_6: THREE.Mesh;
		Object_7: THREE.Mesh;
		Object_8: THREE.Mesh;
		Object_9: THREE.Mesh;
		Object_10: THREE.Mesh;
		Object_11: THREE.Mesh;
		Object_12: THREE.Mesh;
		Object_13: THREE.Mesh;
		Object_14: THREE.Mesh;
		Object_15: THREE.Mesh;
		Object_16: THREE.Mesh;
		Object_17: THREE.Mesh;
		Object_18: THREE.Mesh;
		Object_19: THREE.Mesh;
		Object_20: THREE.Mesh;
		Object_21: THREE.Mesh;
		Object_22: THREE.Mesh;
		Object_23: THREE.Mesh;
		Object_24: THREE.Mesh;
		Object_25: THREE.Mesh;
		Object_26: THREE.Mesh;
		Object_27: THREE.Mesh;
		Object_28: THREE.Mesh;
		Object_29: THREE.Mesh;
		Object_30: THREE.Mesh;
		Object_31: THREE.Mesh;
		Object_32: THREE.Mesh;
		Object_33: THREE.Mesh;
		Object_34: THREE.Mesh;
		Object_35: THREE.Mesh;
		Object_36: THREE.Mesh;
		Object_37: THREE.Mesh;
		Object_38: THREE.Mesh;
		Object_39: THREE.Mesh;
		Object_40: THREE.Mesh;
		Object_41: THREE.Mesh;
		Object_42: THREE.Mesh;
		Object_43: THREE.Mesh;
		Object_44: THREE.Mesh;
		Object_45: THREE.Mesh;
	};
	materials: {
		["Material.002"]: THREE.MeshStandardMaterial;
		["Material.009"]: THREE.MeshPhysicalMaterial;
		["Material.012"]: THREE.MeshStandardMaterial;
		["Material.017"]: THREE.MeshStandardMaterial;
		["Material.019"]: THREE.MeshStandardMaterial;
		["Material.013"]: THREE.MeshStandardMaterial;
		["Material.034"]: THREE.MeshStandardMaterial;
		["Material.030"]: THREE.MeshStandardMaterial;
		["Material.026"]: THREE.MeshStandardMaterial;
		["Material.028"]: THREE.MeshStandardMaterial;
		["Material.039"]: THREE.MeshStandardMaterial;
		["Material.046"]: THREE.MeshStandardMaterial;
		["Material.048"]: THREE.MeshStandardMaterial;
		["plate_d-dds"]: THREE.MeshStandardMaterial;
		["Material.001"]: THREE.MeshPhysicalMaterial;
		Material: THREE.MeshPhysicalMaterial;
		["Material.003"]: THREE.MeshStandardMaterial;
		["Material.006"]: THREE.MeshStandardMaterial;
		["Material.007"]: THREE.MeshStandardMaterial;
		["Material.005"]: THREE.MeshStandardMaterial;
		["Material.011"]: THREE.MeshStandardMaterial;
		["Material.016"]: THREE.MeshStandardMaterial;
		["Material.018"]: THREE.MeshStandardMaterial;
		["Material.023"]: THREE.MeshStandardMaterial;
		["Material.021"]: THREE.MeshStandardMaterial;
		["Material.025"]: THREE.MeshStandardMaterial;
		["Material.035"]: THREE.MeshStandardMaterial;
		["Material.029"]: THREE.MeshStandardMaterial;
		["Material.024"]: THREE.MeshStandardMaterial;
		["Material.037"]: THREE.MeshStandardMaterial;
		["Material.043"]: THREE.MeshStandardMaterial;
		["Material.042"]: THREE.MeshStandardMaterial;
		["Material.044"]: THREE.MeshStandardMaterial;
	};
};

export const Z_s30 = (props: JSX.IntrinsicElements["group"]) => {
	const { nodes, materials } = useGLTF("model/z_s30/scene.gltf") as any as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<mesh geometry={nodes.Object_2.geometry} material={materials["Material.002"]} />
				<mesh geometry={nodes.Object_3.geometry} material={materials["Material.009"]} />
				<mesh geometry={nodes.Object_4.geometry} material={materials["Material.012"]} />
				<mesh geometry={nodes.Object_5.geometry} material={materials["Material.017"]} />
				<mesh geometry={nodes.Object_6.geometry} material={materials["Material.019"]} />
				<mesh geometry={nodes.Object_7.geometry} material={materials["Material.013"]} />
				<mesh geometry={nodes.Object_8.geometry} material={materials["Material.034"]} />
				<mesh geometry={nodes.Object_9.geometry} material={materials["Material.030"]} />
				<mesh geometry={nodes.Object_10.geometry} material={materials["Material.026"]} />
				<mesh geometry={nodes.Object_11.geometry} material={materials["Material.028"]} />
				<mesh geometry={nodes.Object_12.geometry} material={materials["Material.039"]} />
				<mesh geometry={nodes.Object_13.geometry} material={materials["Material.046"]} />
				<mesh geometry={nodes.Object_14.geometry} material={materials["Material.048"]} />
				<mesh geometry={nodes.Object_15.geometry} material={materials["plate_d-dds"]} />
				<mesh geometry={nodes.Object_16.geometry} material={materials["Material.001"]} />
				<mesh geometry={nodes.Object_17.geometry} material={materials["Material.001"]} />
				<mesh geometry={nodes.Object_18.geometry} material={materials.Material} />
				<mesh geometry={nodes.Object_19.geometry} material={materials["Material.003"]} />
				<mesh geometry={nodes.Object_20.geometry} material={materials["Material.003"]} />
				<mesh geometry={nodes.Object_21.geometry} material={materials["Material.006"]} />
				<mesh geometry={nodes.Object_22.geometry} material={materials["Material.007"]} />
				<mesh geometry={nodes.Object_23.geometry} material={materials["Material.005"]} />
				<mesh geometry={nodes.Object_24.geometry} material={materials["Material.011"]} />
				<mesh geometry={nodes.Object_25.geometry} material={materials["Material.011"]} />
				<mesh geometry={nodes.Object_26.geometry} material={materials["Material.011"]} />
				<mesh geometry={nodes.Object_27.geometry} material={materials["Material.011"]} />
				<mesh geometry={nodes.Object_28.geometry} material={materials["Material.016"]} />
				<mesh geometry={nodes.Object_29.geometry} material={materials["Material.018"]} />
				<mesh geometry={nodes.Object_30.geometry} material={materials["Material.023"]} />
				<mesh geometry={nodes.Object_31.geometry} material={materials["Material.023"]} />
				<mesh geometry={nodes.Object_32.geometry} material={materials["Material.023"]} />
				<mesh geometry={nodes.Object_33.geometry} material={materials["Material.023"]} />
				<mesh geometry={nodes.Object_34.geometry} material={materials["Material.021"]} />
				<mesh geometry={nodes.Object_35.geometry} material={materials["Material.021"]} />
				<mesh geometry={nodes.Object_36.geometry} material={materials["Material.025"]} />
				<mesh geometry={nodes.Object_37.geometry} material={materials["Material.035"]} />
				<mesh geometry={nodes.Object_38.geometry} material={materials["Material.035"]} />
				<mesh geometry={nodes.Object_39.geometry} material={materials["Material.029"]} />
				<mesh geometry={nodes.Object_40.geometry} material={materials["Material.024"]} />
				<mesh geometry={nodes.Object_41.geometry} material={materials["Material.037"]} />
				<mesh geometry={nodes.Object_42.geometry} material={materials["Material.043"]} />
				<mesh geometry={nodes.Object_43.geometry} material={materials["Material.043"]} />
				<mesh geometry={nodes.Object_44.geometry} material={materials["Material.042"]} />
				<mesh geometry={nodes.Object_45.geometry} material={materials["Material.044"]} />
			</group>
		</group>
	);
};

useGLTF.preload("model/z_s30/scene.gltf");
